/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ClientesDAO;
import DAO.ProdutosDAO;
import DAO.VendaProdutosDAO;
import DAO.VendasDAO;
import DAO.VendedorDAO;
import bean.Clientes;
import bean.Produtos;
import bean.VendaProdutos;
import bean.Vendas;
import bean.Vendedor;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import tools.Util;
import tools.VendasProdutosController;

/**
 *
 * @author eniof
 */
public class JDlgVendas extends javax.swing.JDialog {
    
    private VendasProdutosController vendasProdutosController;
    private List<VendaProdutos> listaVendaProduto; 
    private Vendas vendas;
    private VendasDAO vendasDAO;
    private ProdutosDAO produtosDAO;
    private ClientesDAO clientesDAO;
    private VendedorDAO vendedorDAO;
    private VendaProdutosDAO vendaProdutosDAO;
    private boolean incluindo;
    
    public JDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        listaVendaProduto = new ArrayList<>();
        vendasProdutosController = new VendasProdutosController();
        initComponents();
        setTitle("Lançamento de Vendas");
        setLocationRelativeTo(null);
        jTextTotal.setEditable(false);
        jTextTotal.setBackground(new java.awt.Color(225, 225, 225));
        vendasDAO = new VendasDAO();
        produtosDAO = new ProdutosDAO();
        clientesDAO = new ClientesDAO();
        vendedorDAO = new VendedorDAO();
        vendaProdutosDAO = new VendaProdutosDAO();

        vendasProdutosController.setList(listaVendaProduto);
        jTable1.setModel(vendasProdutosController);
        defineEstadoInicial();
    }

    private void carregarCombos() {
        List<Clientes> listaClientes = clientesDAO.listAll();
        jCboCliente.removeAllItems();
        for (Clientes cliente : listaClientes) {
            jCboCliente.addItem(cliente);
        }
        
        List<Vendedor> listaVendedores = vendedorDAO.listAll();
        jCboVendedor.removeAllItems();
        for (Vendedor vendedor : listaVendedores) {
            jCboVendedor.addItem(vendedor);
        }
    }
    
    public Vendas viewBean() {
    Vendas venda = new Vendas();
    venda.setClientes((Clientes) jCboCliente.getSelectedItem());
    venda.setVendedor((Vendedor) jCboVendedor.getSelectedItem());
    venda.setDataVenda(Util.strToDate(jFmtData.getText()));
    String totalStr = jTextTotal.getText().replace("R$ ", "").replace(".", "").replace(",", ".");
    if (!totalStr.isEmpty()) {
        venda.setValorTotal(new BigDecimal(totalStr));
    } else {
        venda.setValorTotal(BigDecimal.ZERO);
    }
    
    return venda;
    }
    
    public void beanView(Vendas vendas) {
    this.vendas = vendas;
    jCboCliente.setSelectedItem(vendas.getClientes());
    jCboVendedor.setSelectedItem(vendas.getVendedor());
    
    jFmtData.setText(Util.dateToStr(vendas.getDataVenda()));
    jTextTotal.setText(vendas.getValorTotal().toPlainString());
    VendaProdutosDAO vendaProdutosDAO = new VendaProdutosDAO();
    listaVendaProduto = vendaProdutosDAO.listByVenda(vendas); 
    vendasProdutosController.setList(listaVendaProduto);
    
    recalcularTotal();
}
    
    public void defineEstadoInicial() {
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
        Util.habilitar(false, jBtnAlterar, jBtnExcluir, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(false, jTextCodigo, jFmtData, jCboCliente, jCboVendedor, jTextQuantidade, jTextTotal);
        Util.limpaCampos(jTextCodigo, jFmtData, jTextQuantidade, jTextTotal);
        jCboCliente.setSelectedIndex(-1);
        jCboVendedor.setSelectedIndex(-1);
        listaVendaProduto.clear();
        vendasProdutosController.fireTableDataChanged();
        recalcularTotal();
    }
    
    private void recalcularTotal() {
        BigDecimal total = BigDecimal.ZERO;
        for (VendaProdutos vp : listaVendaProduto) {
            BigDecimal subtotal = vp.getValorUnitario().multiply(new BigDecimal(vp.getQuantidade()));
            total = total.add(subtotal);
        }
        NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        jTextTotal.setText(formatoMoeda.format(total));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jCboCliente = new javax.swing.JComboBox<>();
        jCboVendedor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextQuantidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextTotal = new javax.swing.JTextField();
        jFmtData = new javax.swing.JFormattedTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(196, 196, 196));
        jLabel1.setText("VENDAS");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setText("Vendedor");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setText("Data");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setText("Cliente");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setText("Codigo do Livro");

        jTextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnConfirmar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnConfirmar.setText("Salvar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");

        jBtnIncluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jCboVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboVendedorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setText("Quantidade");

        jTextQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuantidadeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel7.setText("Total");

        jFmtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(316, 316, 316))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextQuantidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel7)
                                .addGap(19, 85, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnIncluir)
                        .addGap(2, 2, 2)
                        .addComponent(jBtnPesquisar)
                        .addGap(2, 2, 2)
                        .addComponent(jBtnAlterar)
                        .addGap(2, 2, 2)
                        .addComponent(jBtnConfirmar)
                        .addGap(2, 2, 2)
                        .addComponent(jBtnCancelar)
                        .addGap(2, 2, 2)
                        .addComponent(jBtnExcluir)))
                .addGap(0, 116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jBtnAlterar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        if (jCboCliente.getSelectedIndex() == -1) {
        Util.mostrar("Selecione um cliente.");
        return;
    }
    if (jCboVendedor.getSelectedIndex() == -1) {
        Util.mostrar("Selecione um vendedor.");
        return;
    }
    if (listaVendaProduto.isEmpty()) {
        Util.mostrar("A venda precisa ter pelo menos um item.");
        return;
    }
    Vendas vendas = new Vendas();
    vendas.setClientes((Clientes) jCboCliente.getSelectedItem());
    vendas.setVendedor((Vendedor) jCboVendedor.getSelectedItem());
    vendas.setDataVenda(new Date());
    String totalStr = jTextTotal.getText().replace("R$ ", "").replace(".", "").replace(",", ".");
    vendas.setValorTotal(new BigDecimal(totalStr));
    try {
        vendasDAO.insert(vendas);
        VendaProdutosDAO vendaProdutosDAO = new VendaProdutosDAO();
        for (VendaProdutos item : listaVendaProduto) {
            item.setVenda(vendas); 
            vendaProdutosDAO.insert(item);
        }
        
        Util.mostrar("Venda salva com sucesso!");
        defineEstadoInicial();

    } catch (Exception e) {
        Util.mostrar("Ocorreu um erro ao salvar a venda: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
    JDlgPesquisaVendas jDlgPesquisa = new JDlgPesquisaVendas(null, true, this);
    jDlgPesquisa.setVisible(true);
    Util.habilitar(true, jBtnAlterar, jBtnExcluir, jBtnCancelar);
    Util.habilitar(false, jBtnIncluir, jBtnConfirmar, jBtnPesquisar);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Util.habilitar(true, jTextCodigo, jFmtData, jCboCliente, jCboVendedor, jTextQuantidade, jTextTotal, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(false,jBtnPesquisar, jBtnIncluir, jBtnAlterar, jBtnExcluir);
        Util.limpaCampos(jTextCodigo, jFmtData, jCboCliente, jCboVendedor, jTextQuantidade, jTextTotal);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jFmtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        Util.habilitar(false, jTextCodigo, jFmtData, jCboCliente, jCboVendedor, jTextQuantidade, jTextTotal, jBtnConfirmar, jBtnCancelar);
        Util.limpaCampos(jTextCodigo, jFmtData, jCboCliente, jCboVendedor, jTextQuantidade, jTextTotal);
            incluindo = false;
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigoActionPerformed

    private void jCboVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboVendedorActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jTextQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuantidadeActionPerformed
    String codigoLivroStr = jTextCodigo.getText();
    if (codigoLivroStr.isEmpty()) {
        Util.mostrar("Primeiro, digite um código de produto.");
        jTextCodigo.requestFocus();
        return;
    }
    Produtos produtos = produtosDAO.findByCodigoLivro(codigoLivroStr);

    if (produtos != null) {
        String qtdStr = jTextQuantidade.getText();
        if (qtdStr.isEmpty()) {
            Util.mostrar("Digite a quantidade.");
            return;
        }

        try {
            int quantidade = Integer.parseInt(qtdStr);
            VendaProdutos vp = new VendaProdutos();
            vp.setProduto(produtos);
            vp.setQuantidade(quantidade);
            vp.setValorUnitario(produtos.getPreco()); 
            listaVendaProduto.add(vp);
            vendasProdutosController.fireTableDataChanged();
            jTextCodigo.setText("");
            jTextCodigo.requestFocus();

            recalcularTotal();

        } catch (NumberFormatException e) {
            Util.mostrar("Quantidade inválida. Por favor, digite apenas números.");
        }
    } else {
        Util.mostrar("Produto com o código " + codigoLivroStr + " não encontrado.");

    }//GEN-LAST:event_jTextQuantidadeActionPerformed

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<Clientes> jCboCliente;
    private javax.swing.JComboBox<Vendedor> jCboVendedor;
    private javax.swing.JFormattedTextField jFmtData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextQuantidade;
    private javax.swing.JTextField jTextTotal;
    // End of variables declaration//GEN-END:variables
}
