package bean;
// Generated 22/09/2025 12:00:35 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Livro generated by hbm2java
 */
@Entity
@Table(name="livro"
    ,catalog="meu_banco"
    , uniqueConstraints = @UniqueConstraint(columnNames="codigo_livro") 
)
public class Livro  implements java.io.Serializable {
     
@Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id_livro", unique=true, nullable=false)
     private int idLivro;
     @Column(name="titulo", nullable=false)
     private String titulo;
     @Column(name="codigo_livro", unique=true, nullable=false, length=30)
     private String codigoLivro;
     @Temporal(TemporalType.DATE)
     @Column(name="ano_publicacao", nullable=false, length=0)
     private Date anoPublicacao;
     @Column(name="genero", nullable=false, length=50)
     private String genero;
     @Column(name="autor", nullable=false, length=50)
     private String autor;
     @Column(name="editora", nullable=false, length=50)
     private String editora;
     @Column(name="preco", nullable=false, precision=10)
     private double preco;

    public Livro() {
    }

	
    public Livro(String titulo, String codigoLivro, Date anoPublicacao, String genero, String autor, String editora, double preco) {
        this.titulo = titulo;
        this.codigoLivro = codigoLivro;
        this.anoPublicacao = anoPublicacao;
        this.genero = genero;
        this.autor = autor;
        this.editora = editora;
        this.preco = preco;
    }
    public Livro(String titulo, String codigoLivro, Date anoPublicacao, String genero, String autor, String editora, double preco, Set vendaProdutos) {
       this.titulo = titulo;
       this.codigoLivro = codigoLivro;
       this.anoPublicacao = anoPublicacao;
       this.genero = genero;
       this.autor = autor;
       this.editora = editora;
       this.preco = preco;
    }
   
    public int getIdLivro() {
        return this.idLivro;
    }
    
    public void setIdLivro(int idLivro) {
        this.idLivro = idLivro;
    }

    
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    public String getCodigoLivro() {
        return this.codigoLivro;
    }
    
    public void setCodigoLivro(String codigoLivro) {
        this.codigoLivro = codigoLivro;
    }

    public Date getAnoPublicacao() {
        return this.anoPublicacao;
    }
    
    public void setAnoPublicacao(Date anoPublicacao) {
        this.anoPublicacao = anoPublicacao;
    }

    
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }

    
    public String getEditora() {
        return this.editora;
    }
    
    public void setEditora(String editora) {
        this.editora = editora;
    }

    
    public double getPreco() {
        return this.preco;
    }
    
    public void setPreco(double preco) {
        this.preco = preco;
    }
}