package bean;
// Generated 22/09/2025 12:00:35 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="meu_banco"
    , uniqueConstraints = {@UniqueConstraint(columnNames="apelido"), @UniqueConstraint(columnNames={"cpf", "rg"})} 
)
public class Usuarios  implements java.io.Serializable {


     private int idUsuario;
     private String nome;
     private String apelido;
     private String cpf;
     private String rg;
     private Date dataNascimento;
     private String nivelAcesso;
     private String senha;
     private boolean ativo;

    public Usuarios() {
    }

	
    public Usuarios(String nome, String apelido, String cpf, String rg, Date dataNascimento, String nivelAcesso, String senha, boolean ativo) {
        this.nome = nome;
        this.apelido = apelido;
        this.cpf = cpf;
        this.rg = rg;
        this.dataNascimento = dataNascimento;
        this.nivelAcesso = nivelAcesso;
        this.senha = senha;
        this.ativo = ativo;
    }
    public Usuarios(String nome, String apelido, String cpf, String rg, Date dataNascimento, String nivelAcesso, String senha, boolean ativo, Set vendas) {
       this.nome = nome;
       this.apelido = apelido;
       this.cpf = cpf;
       this.rg = rg;
       this.dataNascimento = dataNascimento;
       this.nivelAcesso = nivelAcesso;
       this.senha = senha;
       this.ativo = ativo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="nome", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="apelido", unique=true, nullable=false, length=50)
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }

    
    @Column(name="cpf", nullable=false, length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="rg", nullable=false, length=20)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento", nullable=false, length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="nivel_acesso", nullable=false, length=50)
    public String getNivelAcesso() {
        return this.nivelAcesso;
    }
    
    public void setNivelAcesso(String nivelAcesso) {
        this.nivelAcesso = nivelAcesso;
    }

    
    @Column(name="senha", nullable=false, length=50)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="ativo", nullable=false)
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
}


