package bean;
// Generated 22/09/2025 12:00:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vendedor generated by hbm2java
 */
@Entity
@Table(name="vendedor"
    ,catalog="meu_banco"
)
public class Vendedor  implements java.io.Serializable {


     private int idVendedor;
     private String nome;
     private String cpf;
     private String rg;
     private String cnpj;
     private String email;
     private String telefone;
     private String cep;
     private String numero;
     private String endereco;
     private String estado;
     private String cidade;

    public Vendedor() {
    }

    public Vendedor(String nome, String cpf, String rg, String cnpj, String email, String telefone, String cep, String numero, String endereco, String estado, String cidade) {
       this.nome = nome;
       this.cpf = cpf;
       this.rg = rg;
       this.cnpj = cnpj;
       this.email = email;
       this.telefone = telefone;
       this.cep = cep;
       this.numero = numero;
       this.endereco = endereco;
       this.estado = estado;
       this.cidade = cidade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_vendedor", unique=true, nullable=false)
    public int getIdVendedor() {
        return this.idVendedor;
    }
    
    public void setIdVendedor(int idVendedor) {
        this.idVendedor = idVendedor;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="cpf", nullable=false, length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="rg", nullable=false, length=20)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="cnpj", nullable=false, length=20)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="email", nullable=false, length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="telefone", nullable=false, length=20)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="cep", nullable=false, length=20)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="numero", nullable=false, length=50)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="endereco", nullable=false, length=200)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="estado", nullable=false, length=30)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="cidade", nullable=false, length=30)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }




}


