package bean;
// Generated 22/09/2025 12:00:35 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venda generated by hbm2java
 */
@Entity
@Table(name="venda"
    ,catalog="meu_banco"
)
public class Venda  implements java.io.Serializable {


     private int idVenda;
     private Clientes cliente;
     private Usuarios usuario;
     private Date dataVenda;
     private double valorTotal;
     
    public Venda() {
    }

	
    public Venda(Clientes cliente, Usuarios usuario, Date dataVenda, double valorTotal) {
        this.cliente = cliente;
        this.usuario = usuario;
        this.dataVenda = dataVenda;
        this.valorTotal = valorTotal;
    }
    public Venda(Clientes cliente, Usuarios usuario, Date dataVenda, double valorTotal, Set vendaProdutos) {
       this.cliente = cliente;
       this.usuario = usuario;
       this.dataVenda = dataVenda;
       this.valorTotal = valorTotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_venda", unique=true, nullable=false)
    public int getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(int idVenda) {
        this.idVenda = idVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_cliente", nullable=false)
    public Clientes getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Clientes cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_vendedor", nullable=false)
    public Usuarios getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuarios usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_venda", nullable=false, length=19)
    public Date getDataVenda() {
        return this.dataVenda;
    }
    
    public void setDataVenda(Date dataVenda) {
        this.dataVenda = dataVenda;
    }

    
    @Column(name="valor_total", nullable=false, precision=10)
    public double getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(double valorTotal) {
        this.valorTotal = valorTotal;
    }
}


